#release configuration
#Sun Mar 08 09:38:35 JST 2026
completedPhase=check-poms
exec.pomFileName=pom.xml
exec.snapshotReleasePluginAllowed=false
pinExternals=false
preparationGoals=clean verify
project.scm.llc.livlog.wazahyo\:wazahyo.connection=scm\:git\:git@github.com\:livlog-llc/wazahyo.git
project.scm.llc.livlog.wazahyo\:wazahyo.tag=HEAD
project.scm.llc.livlog.wazahyo\:wazahyo.url=https\://github.com/livlog-llc/wazahyo
projectVersionPolicyConfig=<projectVersionPolicyConfig>${projectVersionPolicyConfig}</projectVersionPolicyConfig>\n
projectVersionPolicyId=default
pushChanges=true
releaseStrategyId=default
remoteTagging=true
scm.branchCommitComment=@{prefix} prepare branch @{releaseLabel}
scm.commentPrefix=[Release]
scm.developmentCommitComment=@{prefix} prepare for next development iteration
scm.releaseCommitComment=@{prefix} prepare release @{releaseLabel}
scm.rollbackCommitComment=@{prefix} rollback the release of @{releaseLabel}
scm.tagNameFormat=v@{project.version}
scm.url=scm\:git\:git@github.com\:livlog-llc/wazahyo.git
